preload = /usr/share/sddm/themes/ii-sddm-theme/Backgrounds/background.png
wallpaper {
    monitor = eDP-1
    path = /usr/share/sddm/themes/ii-sddm-theme/Backgrounds/background.png
    fit_mode = cover
}
splash = false
